export const notableVenues: string[] = [
  "CSUR",
  "IEEE Access",
  "IEEE TETCI",
  "Radiology",
  "SIGKDD",
  "ICDM",
  "ICMLA",
  "ICDE",
  "BIBM",
];

export interface PublicationProps {
  id?: string;
  year: number;
  title: string;
  authors: string[];
  venue: string;
  specialIssue?: string;
  type:
    | "Journal"
    | "Conference"
    | "Book"
    | "Book Chapter"
    | "Preprint"
    | "Other";

  workshop?: string;
  award?: string;
  abstract?: string;
  link?: string;
  pdf?: string;
}

export const Publications: PublicationProps[] = [
  {
    id: "https://openalex.org/W4415749046",
    year: 2025,
    title:
      "A Multiagent Summarization and Auto-Evaluation Framework for Medical Text: Development and Evaluation Study",
    authors: ["Chen, Y.", "Wen, B.", "Zulkernine, F."],
    venue: "JMIR AI",
    type: "Journal",
    link: "https://doi.org/10.2196/75932",
  },
  {
    id: "https://openalex.org/W4413968650",
    year: 2025,
    title:
      "CNN-CCA: A deep learning approach for anomaly detection in metro rail sensor time-series data",
    authors: [
      "Rao, V.",
      "Eskandari, A.",
      "Zulkernine, F.",
      "Helwa, M.",
      "Beach, D.",
    ],
    venue: "Machine Learning with Applications",
    type: "Journal",
    link: "https://doi.org/10.1016/j.mlwa.2025.100728",
  },
  {
    id: "https://openalex.org/W4413862749",
    year: 2025,
    title:
      "A two-phase hybrid clustering framework exploring transitional activities in HAR",
    authors: ["Woo, M.", "Harby, A.", "Zulkernine, F.", "Abdulsalam, H."],
    venue: "Discover Artificial Intelligence",
    type: "Journal",
    link: "https://doi.org/10.1007/s44163-025-00503-6",
    pdf: "https://link.springer.com/content/pdf/10.1007/s44163-025-00503-6.pdf",
  },
  {
    year: 2025,
    title: "Transformer-based human action recognition using skeleton heatmap",
    authors: ["Teng, A.", "Anand, A.", "Zulkernine, F."],
    venue:
      "15th International Conference on Current and Future Trends of Information and Communication Technologies in Healthcare (ITCH)",
    type: "Conference",
    link: "https://doi.org/10.1016/j.procs.2025.10.265",
  },
  {
    id: "https://openalex.org/W4413679495",
    year: 2025,
    title:
      "SDA-GRIN for Adaptive Spatial-Temporal Multivariate Time Series Imputation",
    authors: ["Eskandari, A.", "Anand, A.", "Sharma, D.", "Zulkernine, F."],
    venue:
      "2025 IEEE 49th Annual Computers, Software, and Applications Conference (COMPSAC)",
    type: "Conference",
    link: "https://doi.org/10.1109/compsac65507.2025.00246",
  },
  {
    id: "https://openalex.org/W4413679396",
    year: 2025,
    title:
      "Automatic Diagnosis of Hip and Knee Osteoarthritis from Medical Text Records",
    authors: [
      "Cai, J.",
      "Kokel, V.",
      "Zulkernine, F.",
      "Queenan, J.",
      "Barber, D.",
    ],
    venue:
      "2025 IEEE 49th Annual Computers, Software, and Applications Conference (COMPSAC)",
    type: "Conference",
    link: "https://doi.org/10.1109/compsac65507.2025.00108",
  },
  {
    id: "https://openalex.org/W4413680132",
    year: 2025,
    title:
      "Towards a Voice-Adaptive LLM-Based Conversation Bot for Enhanced User Interaction",
    authors: [
      "Eskandari, A.",
      "Monir, T.",
      "Zulkernine, F.",
      "Morningstar, M.",
      "Poppenk, J.",
      "Herrmann, B.",
    ],
    venue:
      "2025 IEEE 49th Annual Computers, Software, and Applications Conference (COMPSAC)",
    type: "Conference",
    link: "https://doi.org/10.1109/compsac65507.2025.00276",
  },
  {
    id: "https://openalex.org/W4413269998",
    year: 2025,
    title:
      "Diagnosis and Management of Alzheimer’s Disease in Primary Care: A Real-World Study in Ontario, Canada",
    authors: [
      "Ismail, Z.",
      "Wilson, M.",
      "Khalifa, H.",
      "Belovich, D.",
      "Shaw, E.",
      "Pham, T.",
      "McMullen, S.",
      "Chen, Y.",
      "Sadman, N.",
      "Cai, J.",
      "Zulkernine, F.",
      "Barber, D.",
    ],
    venue: "Journal of Primary Care & Community Health",
    type: "Journal",
    link: "https://doi.org/10.1177/21501319251363156",
  },
  {
    id: "https://openalex.org/W4415311592",
    year: 2025,
    title:
      "Interpreting Biomedical VLMs on High-Imbalance Out-of-Distributions: An Insight into BiomedCLIP on Radiology",
    authors: ["Sadman, N.", "Zulkernine, F.", "Kwan, B."],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "http://arxiv.org/abs/2506.14136",
    pdf: "https://arxiv.org/pdf/2506.14136",
  },
  {
    id: "https://openalex.org/W4409887133",
    year: 2025,
    title:
      "A Multi-agent Large Language Model Framework for Medical Text Summarization and Evaluation: Development and Evaluation Study (Preprint)",
    authors: ["Chen, Y.", "Wen, B.", "Zulkernine, F."],
    venue: "Preprint",
    type: "Preprint",
    link: "https://doi.org/10.2196/preprints.75932",
  },
  {
    id: "https://openalex.org/W4409402469",
    year: 2025,
    title: "Legal Text Analytics for Reasonable Notice Period Prediction",
    authors: ["Lam, J.", "Chen, Y.", "Zulkernine, F.", "Dahan, S."],
    venue: "Journal of Computational and Cognitive Engineering",
    type: "Journal",
    link: "https://doi.org/10.47852/bonviewjcce52024104",
    pdf: "https://ojs.bonviewpress.com/index.php/JCCE/article/download/4104/1364",
  },
  {
    id: "https://openalex.org/W4411360010",
    year: 2025,
    title:
      "Swin PoseFormer: A Human Activity Recognition Model Using Skeleton Heatmaps",
    authors: ["Qi, H.", "Zhang, Z.", "Zulkernine, F."],
    venue:
      "2025 IEEE Symposium on Computational Intelligence in Image, Signal Processing and Synthetic Media Companion (CISM Companion)",
    type: "Journal",
    link: "https://doi.org/10.1109/cismcompanion65074.2025.11032343",
  },
  {
    id: "https://openalex.org/W4407468749",
    year: 2024,
    title:
      "CoBEVFusion Cooperative Perception with LiDAR-Camera Bird's Eye View Fusion",
    authors: ["Qiao, D.", "Zulkernine, F.", "Anand, A."],
    venue:
      "2024 International Conference on Digital Image Computing: Techniques and Applications (DICTA)",
    type: "Conference",
    link: "https://doi.org/10.1109/dicta63115.2024.00064",
  },
  {
    id: "https://openalex.org/W4404628971",
    year: 2024,
    title:
      "SKELETRACK: Efficient Tracking of Skeleton in Blurry Videos for Human Activity Recognition",
    authors: ["Qi, H.", "Zhang, Z.", "Zulkernine, F."],
    venue: "2024 7th Conference on Cloud and Internet of Things (CIoT)",
    type: "Conference",
    link: "http://doi.org/10.1109/ciot63799.2024.10756983",
  },
  {
    id: "https://openalex.org/W4403730650",
    year: 2024,
    title:
      "YOLO-I3D: Optimizing Inflated 3D Models for Real-Time Human Activity Recognition",
    authors: ["Luo, R.", "Anand, A.", "Zulkernine, F.", "Rivest, F."],
    venue: "Journal of Imaging",
    type: "Journal",
    link: "https://doi.org/10.3390/jimaging10110269",
  },
  {
    id: "https://openalex.org/W4404088355",
    year: 2024,
    title:
      "Depth-Guided Self-Supervised Human Keypoint Detection via Cross-Modal Distillation",
    authors: ["Anand, A.", "Rashno, E.", "Eskandari, A.", "Zulkernine, F."],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "http://arxiv.org/abs/2410.14700",
    pdf: "https://arxiv.org/pdf/2410.14700",
  },
  {
    id: "https://openalex.org/W4403322307",
    year: 2024,
    title:
      "SDA-GRIN for Adaptive Spatial-Temporal Multivariate Time Series Imputation",
    authors: ["Eskandari, A.", "Anand, A.", "Sharma, D.", "Zulkernine, F."],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "http://arxiv.org/abs/2410.03954",
    pdf: "https://arxiv.org/pdf/2410.03954",
  },
  {
    id: "https://openalex.org/W4402898151",
    year: 2024,
    title: "Data Lakehouse: A survey and experimental study",
    authors: ["Harby, A.", "Zulkernine, F."],
    venue: "Information Systems",
    type: "Journal",
    link: "https://doi.org/10.1016/j.is.2024.102460",
  },
  {
    id: "https://openalex.org/W4401672261",
    year: 2024,
    title:
      "Implementing Triage-Bot: Supporting the Current Practice for Triage Nurses",
    authors: [
      "Sears, K.",
      "Belbin, S.",
      "Rashno, E.",
      "Sharma, D.",
      "Woo, K.",
      "Zulkernine, F.",
      "Neagu, C.",
      "Amani, B.",
      "Alaca, F.",
    ],
    venue: "Surgical Technology Online",
    type: "Journal",
    link: "https://doi.org/10.52198/24.sti.44.wh1804",
  },
  {
    id: "https://openalex.org/W4401943523",
    year: 2024,
    title: "Triage-Bot: An Assistive Triage Framework",
    authors: [
      "Sharma, D.",
      "Rashno, E.",
      "Zulkernine, F.",
      "Khodary, E.",
      "Beninger, M.",
      "Almeida, R.",
      "Tao, J.",
      "Alaca, F.",
      "Elgazzar, K.",
    ],
    venue: "2024 IEEE International Conference on Digital Health (ICDH)",
    type: "Conference",
    link: "http://doi.org/10.1109/icdh62654.2024.00033",
  },
  {
    id: "https://openalex.org/W4401943355",
    year: 2024,
    title:
      "Leveraging Large Language Models for Patient Engagement: The Power of Conversational AI in Digital Health",
    authors: [
      "Wen, B.",
      "Norel, R.",
      "Liu, J.",
      "Stappenbeck, T.",
      "Zulkernine, F.",
      "Chen, H.",
    ],
    venue: "2024 IEEE International Conference on Digital Health (ICDH)",
    type: "Conference",
    link: "https://doi.org/10.1109/icdh62654.2024.00027",
  },
  {
    id: "https://openalex.org/W4401943459",
    year: 2024,
    title:
      "Comparative Analysis of Open-Source Language Models in Summarizing Medical Text Data",
    authors: ["Chen, Y.", "Wang, Z.", "Zulkernine, F."],
    venue: "2024 IEEE International Conference on Digital Health (ICDH)",
    type: "Conference",
    link: "https://doi.org/10.1109/icdh62654.2024.00030",
  },
  {
    id: "https://openalex.org/W4401879874",
    year: 2024,
    title:
      "Revolutionizing Healthcare Management: Architecture of a Web-based Medical Triage Service",
    authors: [
      "Harby, A.",
      "ElKhodary, E.",
      "Almeida, R.",
      "Sharma, D.",
      "Zulkernine, F.",
      "Alaca, F.",
      "Elgazzar, K.",
      "Marzouqi, A.",
      "Al‐Yateem, N.",
      "Rahman, S.",
    ],
    venue:
      "2024 IEEE 48th Annual Computers, Software, and Applications Conference (COMPSAC)",
    type: "Conference",
    link: "http://doi.org/10.1109/compsac61105.2024.00299",
  },
  {
    id: "https://openalex.org/W4401879038",
    year: 2024,
    title: "Assist-Bot: A Voice-Enabled Assistant for Seniors",
    authors: [
      "Chen, Y.",
      "Cai, J.",
      "Chen, S.",
      "Zulkernine, F.",
      "Jaffar, N.",
      "Marzouqi, A.",
      "Al‐Yateem, N.",
      "Rahman, S.",
    ],
    venue:
      "2024 IEEE 48th Annual Computers, Software, and Applications Conference (COMPSAC)",
    type: "Conference",
    link: "http://doi.org/10.1109/compsac61105.2024.00301",
  },
  {
    id: "https://openalex.org/W4399913032",
    year: 2024,
    title:
      "Leveraging Large Language Models for Patient Engagement: The Power of Conversational AI in Digital Health",
    authors: [
      "Wen, B.",
      "Norel, R.",
      "Liu, J.",
      "Stappenbeck, T.",
      "Zulkernine, F.",
      "Chen, H.",
    ],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "http://arxiv.org/abs/2406.13659",
    pdf: "https://arxiv.org/pdf/2406.13659",
  },
  {
    id: "https://openalex.org/W4399149716",
    year: 2024,
    title:
      "Comparative Analysis of Open-Source Language Models in Summarizing Medical Text Data",
    authors: ["Chen, Y.", "Wang, Z.", "Wen, B.", "Zulkernine, F."],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "http://arxiv.org/abs/2405.16295",
    pdf: "https://arxiv.org/pdf/2405.16295",
  },
  {
    id: "https://openalex.org/W4401508264",
    year: 2024,
    title:
      "Privacy-Preserving Multi-Party Keyword-Based Classification of Unstructured Text Data",
    authors: ["Pépin, I.", "Alaca, F.", "Zulkernine, F."],
    venue:
      "2024 20th International Conference on Distributed Computing in Smart Systems and the Internet of Things (DCOSS-IoT)",
    type: "Conference",
    link: "https://doi.org/10.1109/dcoss-iot61029.2024.00037",
  },
  {
    id: "https://openalex.org/W4395483151",
    year: 2024,
    title: "Data Lakehouse: A Survey and Experimental Study",
    authors: ["Harby, A.", "Zulkernine, F."],
    venue: "SSRN Electronic Journal",
    type: "Preprint",
    link: "https://doi.org/10.2139/ssrn.4765588",
  },
  {
    id: "https://openalex.org/W4394876673",
    year: 2024,
    title:
      "Skeletrack: Efficient Tracking of Human Skeleton in Blurry Videos for Activity Recognition",
    authors: ["Qi, H.", "Zhang, Z.", "Zulkernine, F."],
    venue: "SSRN Electronic Journal",
    type: "Preprint",
    link: "https://doi.org/10.2139/ssrn.4797438",
  },
  {
    id: "https://openalex.org/W4390489161",
    year: 2023,
    title:
      "Vulnerability of Open-Source Face Recognition Systems to Blackbox Attacks: A Case Study with InsightFace",
    authors: [
      "Sadman, N.",
      "Hasan, K.",
      "Rashno, E.",
      "Alaca, F.",
      "Tian, Y.",
      "Zulkernine, F.",
    ],
    venue: "2023 IEEE Symposium Series on Computational Intelligence (SSCI)",
    type: "Journal",
    link: "https://doi.org/10.1109/ssci52147.2023.10371801",
  },
  {
    id: "https://openalex.org/W4390482122",
    year: 2023,
    title: "An Intelligent Email Classification System",
    authors: ["Luo, Z.", "Zulkernine, F."],
    venue: "2023 IEEE Symposium Series on Computational Intelligence (SSCI)",
    type: "Journal",
    link: "https://doi.org/10.1109/ssci52147.2023.10371921",
  },
  {
    id: "https://openalex.org/W4390481874",
    year: 2023,
    title:
      "Image Caption Generation Based on Image-Text Matching Schema in Deep Reinforcement Learning",
    authors: [
      "Rashno, E.",
      "Safarzadehvahed, M.",
      "Zulkernine, F.",
      "Givigi, S.",
    ],
    venue: "2023 IEEE Symposium Series on Computational Intelligence (SSCI)",
    type: "Journal",
    link: "https://doi.org/10.1109/ssci52147.2023.10371820",
  },
  {
    id: "https://openalex.org/W4387769820",
    year: 2023,
    title:
      "Development and validation of a case definition to estimate the prevalence and incidence of cirrhosis in pan-Canadian primary care databases",
    authors: [
      "Faisal, N.",
      "Kosowan, L.",
      "Zafari, H.",
      "Zulkernine, F.",
      "Lix, L.",
      "Mahar, A.",
      "Singh, H.",
      "Renner, E.",
      "Singer, A.",
    ],
    venue: "Canadian Liver Journal",
    type: "Journal",
    link: "https://doi.org/10.3138/canlivj-2023-0002",
  },
  {
    id: "https://openalex.org/W4387560630",
    year: 2023,
    title:
      "CoBEVFusion: Cooperative Perception with LiDAR-Camera Bird's-Eye View Fusion",
    authors: ["Qiao, D.", "Zulkernine, F."],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "http://arxiv.org/abs/2310.06008",
    pdf: "https://arxiv.org/pdf/2310.06008",
  },
  {
    id: "https://openalex.org/W4386215146",
    year: 2023,
    title:
      "SPaDe: A Synonym-based Pain-level Detection Tool for Osteoarthritis",
    authors: [
      "Chen, Y.",
      "shu, b.",
      "Moattari, M.",
      "Zulkernine, F.",
      "Queenan, J.",
      "Barber, D.",
    ],
    venue: "2023 IEEE International Conference on Digital Health (ICDH)",
    type: "Conference",
    link: "https://doi.org/10.1109/icdh60066.2023.00026",
  },
  {
    id: "https://openalex.org/W4379522978",
    year: 2023,
    title: "I3D Light - A Simple Motion Information Stream for I3D",
    authors: ["Luo, R.", "Rivest, F.", "Zulkernine, F."],
    venue: "Proceedings of the Canadian Conference on Artificial Intelligence",
    type: "Conference",
    link: "https://doi.org/10.21428/594757db.dffcb184",
    pdf: "https://caiac.pubpub.org/pub/fylrbqi5/download/pdf",
  },
  {
    id: "https://openalex.org/W4379523227",
    year: 2023,
    title: "Quantifying Path Smoothness in Video Object Tracking by Detection",
    authors: ["Gasmallah, M.", "Rivest, F.", "Zulkernine, F.", "Breton, M."],
    venue: "Proceedings of the Canadian Conference on Artificial Intelligence",
    type: "Conference",
    link: "https://doi.org/10.21428/594757db.f0bc10fd",
    pdf: "https://caiac.pubpub.org/pub/dxa5hlz5/download/pdf",
  },
  {
    id: "https://openalex.org/W4385489198",
    year: 2023,
    title:
      "Examining Feasibility and Efficacy of Traditional Stream Clustering Algorithms on Complex Human Activity Recognition Data",
    authors: ["Woo, M.", "Zulkernine, F.", "Abdulsalam, H."],
    venue:
      "2023 IEEE 47th Annual Computers, Software, and Applications Conference (COMPSAC)",
    type: "Conference",
    link: "https://doi.org/10.1109/compsac57700.2023.00046",
  },
  {
    id: "https://openalex.org/W4382561988",
    year: 2023,
    title:
      "Guest Editorial: Special Section on Machine Learning and Artificial Intelligence for Managing Networks, Systems, and Services—Part II",
    authors: [
      "Zincir‐Heywood, A.",
      "Birke, R.",
      "Bou‐Harb, E.",
      "Casale, G.",
      "El‐Khatib, K.",
      "Inoue, T.",
      "Kumar, N.",
      "Lutfiyya, H.",
      "Puthal, D.",
      "Shami, A.",
      "Stakhanova, N.",
      "Zulkernine, F.",
    ],
    venue: "IEEE Transactions on Network and Service Management",
    type: "Journal",
    link: "https://doi.org/10.1109/tnsm.2023.3280230",
    pdf: "https://ieeexplore.ieee.org/ielx7/4275028/10168539/10168542.pdf",
  },
  {
    id: "https://openalex.org/W4385489127",
    year: 2023,
    title:
      "A Comparative Analysis of Graph Neural Networks for Fake News Detection",
    authors: ["Harby, A.", "Zulkernine, F."],
    venue:
      "2023 IEEE 47th Annual Computers, Software, and Applications Conference (COMPSAC)",
    type: "Conference",
    link: "https://doi.org/10.1109/compsac57700.2023.00184",
  },
  {
    id: "https://openalex.org/W4322716516",
    year: 2023,
    title:
      "A Preliminary Study on Pattern Reconstruction for Optimal Storage of Wearable Sensor Data",
    authors: ["Mahfuz, S.", "Zulkernine, F."],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "http://arxiv.org/abs/2302.12972",
    pdf: "https://arxiv.org/pdf/2302.12972",
  },
  {
    id: "https://openalex.org/W4319299982",
    year: 2023,
    title:
      "Adaptive Feature Fusion for Cooperative Perception using LiDAR Point Clouds",
    authors: ["Qiao, D.", "Zulkernine, F."],
    venue:
      "2023 IEEE/CVF Winter Conference on Applications of Computer Vision (WACV)",
    type: "Conference",
    link: "https://doi.org/10.1109/wacv56688.2023.00124",
  },
  {
    id: "https://openalex.org/W4385832667",
    year: 2023,
    title: "Efficient Video Captioning with Frame Similarity-Based Filtering",
    authors: ["Rashno, E.", "Zulkernine, F."],
    venue: "Lecture notes in computer science",
    type: "Book Chapter",
    link: "https://doi.org/10.1007/978-3-031-39821-6_7",
  },
  {
    id: "https://openalex.org/W4318185132",
    year: 2022,
    title: "From Data Warehouse to Lakehouse: A Comparative Review",
    authors: ["Harby, A.", "Zulkernine, F."],
    venue: "2022 IEEE International Conference on Big Data (Big Data)",
    type: "Conference",
    link: "https://doi.org/10.1109/bigdata55660.2022.10020719",
  },
  {
    id: "https://openalex.org/W4311029042",
    year: 2022,
    title:
      "Characterizing primary care patients with posttraumatic stress disorder using electronic medical records: a retrospective cross-sectional study",
    authors: [
      "Singer, A.",
      "Kosowan, L.",
      "Muthumuni, D.",
      "Katz, A.",
      "Zafari, H.",
      "Zulkernine, F.",
      "Richardson, J.",
      "Price, M.",
      "Williamson, T.",
      "Queenan, J.",
      "Sareen, J.",
    ],
    venue: "Family Practice",
    type: "Journal",
    link: "https://doi.org/10.1093/fampra/cmac139",
  },
  {
    id: "https://openalex.org/W4318823673",
    year: 2022,
    title:
      "Guest Editorial: Special Issue on Machine Learning and Artificial Intelligence for Managing Networks, Systems, and Services—Part I",
    authors: [
      "Zincir‐Heywood, A.",
      "Birke, R.",
      "Bou‐Harb, E.",
      "Casale, G.",
      "El‐Khatib, K.",
      "Inoue, T.",
      "Kumar, N.",
      "Lutfiyya, H.",
      "Puthal, D.",
      "Shami, A.",
      "Stakhanova, N.",
      "Zulkernine, F.",
    ],
    venue: "IEEE Transactions on Network and Service Management",
    type: "Journal",
    link: "https://doi.org/10.1109/tnsm.2022.3227775",
    pdf: "https://ieeexplore.ieee.org/ielx7/4275028/10034788/10034817.pdf",
  },
  {
    id: "https://openalex.org/W4311503790",
    year: 2022,
    title:
      "Pan-Canadian Electronic Medical Record Diagnostic and Unstructured Text Data for Capturing PTSD: Retrospective Observational Study",
    authors: [
      "Kosowan, L.",
      "Singer, A.",
      "Zulkernine, F.",
      "Zafari, H.",
      "Nesca, M.",
      "Muthumuni, D.",
    ],
    venue: "JMIR Medical Informatics",
    type: "Journal",
    link: "https://doi.org/10.2196/41312",
  },
  {
    id: "https://openalex.org/W4295776058",
    year: 2022,
    title:
      "Natural Language Processing of Computed Tomography Reports to Label Metastatic Phenotypes With Prognostic Significance in Patients With Colorectal Cancer",
    authors: [
      "Andrieu, P.",
      "Pernicka, J.",
      "Yaeger, R.",
      "Lupton, K.",
      "Batch, K.",
      "Zulkernine, F.",
      "Simpson, A.",
      "Taya, M.",
      "Gazit, L.",
      "Nguyen, H.",
      "Nicholas, K.",
      "Gangai, N.",
      "Sevilimedu, V.",
      "Dickinson, S.",
      "Paroder, V.",
      "Bates, ‬.",
      "Gian, R.",
    ],
    venue: "JCO Clinical Cancer Informatics",
    type: "Journal",
    link: "https://doi.org/10.1200/cci.22.00014",
  },
  {
    id: "https://openalex.org/W4292954823",
    year: 2022,
    title:
      "A Web Application for Experimenting and Validating Remote Measurement of Vital Signs",
    authors: ["Ayesha, A.", "Qiao, D.", "Zulkernine, F."],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "http://arxiv.org/abs/2208.09916",
    pdf: "https://arxiv.org/pdf/2208.09916",
  },
  {
    id: "https://openalex.org/W4297644151",
    year: 2022,
    title:
      "ProjB: An Improved Bilinear Biased ProjE model for Knowledge Graph Completion",
    authors: ["Moattari, M.", "Vahdati, S.", "Zulkernine, F."],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "http://arxiv.org/abs/2209.02390",
    pdf: "https://arxiv.org/pdf/2209.02390",
  },
  {
    id: "https://openalex.org/W4292973032",
    year: 2022,
    title: "ICDH 2022 Organizing Committee",
    authors: [
      "Damiani, E.",
      "Ardagna, C.",
      "Zhang, J.",
      "Ahamed, I.",
      "Priami, C.",
      "Pavel, M.",
      "Chairs, I.",
      "Liu, L.",
      "Zulkernine, F.",
      "Bochicchio, M.",
      "Chou, L.",
      "Hsu, T.",
      "Hu, J.",
      "Nugent, C.",
      "Subramanyan, R.",
      "Amazon, W.",
      "Rizzo, J.",
      "Chang, K.",
      "Khan, R.",
      "Parve, F.",
      "Sakatani, K.",
      "Yang, P.",
      "Chang, R.",
      "Chu, W.",
      "Helal, S.",
      "Jain, R.",
      "Takakura, H.",
    ],
    venue: "2022 IEEE International Conference on Digital Health (ICDH)",
    type: "Conference",
    link: "https://doi.org/10.1109/icdh55609.2022.00005",
    pdf: "https://ieeexplore.ieee.org/ielx7/9861038/9861040/09861070.pdf",
  },
  {
    id: "https://openalex.org/W4283212869",
    year: 2022,
    title: "ReViSe: Remote Vital Signs Measurement Using Smartphone Camera",
    authors: [
      "Qiao, D.",
      "Ayesha, A.",
      "Zulkernine, F.",
      "Masroor, R.",
      "Jaffar, N.",
    ],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "http://arxiv.org/abs/2206.08748",
    pdf: "https://arxiv.org/pdf/2206.08748",
  },
  {
    id: "https://openalex.org/W4226377869",
    year: 2022,
    title:
      "Characterizing posttraumatic stress disorder in primary care using electronic medical records: a retrospective cohort study",
    authors: [
      "Muthumuni, D.",
      "Kosowan, L.",
      "Katz, A.",
      "Wong, S.",
      "Richardson, J.",
      "Queenan, J.",
      "Zafari, H.",
      "Singer, A.",
      "Williamson, T.",
      "Zulkernine, F.",
      "Wolfrom, B.",
      "Sareen, J.",
    ],
    venue: "Behavioral, psychosocial, and mental illness",
    type: "Journal",
    link: "https://doi.org/10.1370/afm.20.s1.2815",
    pdf: "https://www.annfammed.org/content/annalsfm/20/Supplement_1/2815.full.pdf",
  },
  {
    id: "https://openalex.org/W4214933629",
    year: 2022,
    title:
      "Developing a Cancer Digital Twin: Supervised Metastases Detection From Consecutive Structured Radiology Reports",
    authors: [
      "Batch, K.",
      "Yue, J.",
      "Darcovich, A.",
      "Lupton, K.",
      "Liu, C.",
      "Woodlock, D.",
      "Amine, M.",
      "Causa-Andrieu, P.",
      "Gazit, L.",
      "Nguyen, G.",
      "Zulkernine, F.",
      "Gian, R.",
      "Simpson, A.",
    ],
    venue: "Frontiers in Artificial Intelligence",
    type: "Journal",
    link: "https://doi.org/10.3389/frai.2022.826402",
    pdf: "https://www.frontiersin.org/articles/10.3389/frai.2022.826402/pdf",
  },
  {
    id: "https://openalex.org/W4312355099",
    year: 2022,
    title: "ReViSe: Remote Vital Signs Measurement Using Smartphone Camera",
    authors: [
      "Qiao, D.",
      "Ayesha, A.",
      "Zulkernine, F.",
      "Jaffar, N.",
      "Masroor, R.",
    ],
    venue: "IEEE Access",
    specialIssue:
      "Special Issue on Computational Intelligence to Edge AI for Ubiquitous IoT Systems",

    type: "Journal",
    link: "https://doi.org/10.1109/access.2022.3229977",
  },
  {
    id: "https://openalex.org/W4312651986",
    year: 2022,
    title:
      "A Web Application for Experimenting and Validating Remote Measurement of Vital Signs",
    authors: ["Ayesha, A.", "Qiao, D.", "Zulkernine, F."],
    venue: "Lecture notes in computer science",
    type: "Book Chapter",
    link: "https://doi.org/10.1007/978-3-031-21047-1_21",
  },
  {
    id: "https://openalex.org/W4214708567",
    year: 2022,
    title: "Predictive Modeling of Diabetes using EMR Data",
    authors: [
      "Zafari, H.",
      "Li, J.",
      "Zulkernine, F.",
      "Kosowan, L.",
      "Singer, A.",
    ],
    venue:
      "Proceedings of the 15th International Joint Conference on Biomedical Engineering Systems and Technologies",
    type: "Conference",
    link: "https://doi.org/10.5220/0010908900003123",
  },
  {
    id: "https://openalex.org/W4206545034",
    year: 2021,
    title:
      "Drivable Area Detection Using Deep Learning Models for Autonomous Driving",
    authors: ["Qiao, D.", "Zulkernine, F."],
    venue: "2021 IEEE International Conference on Big Data (Big Data)",
    type: "Conference",
    link: "https://doi.org/10.1109/bigdata52589.2021.9671392",
  },
  {
    id: "https://openalex.org/W4205795307",
    year: 2021,
    title:
      "BIRD-QA: A BERT-based Information Retrieval Approach to Domain Specific Question Answering",
    authors: ["Chen, Y.", "Zulkernine, F."],
    venue: "2021 IEEE International Conference on Big Data (Big Data)",
    type: "Conference",
    link: "https://doi.org/10.1109/bigdata52589.2021.9671523",
  },
  {
    id: "https://openalex.org/W4205231300",
    year: 2021,
    title: "Predicting the Length of Stay of Patients in Hospitals",
    authors: ["Fu, Z.", "Gu, X.", "Fu, J.", "Moattari, M.", "Zulkernine, F."],
    venue:
      "2021 IEEE International Conference on Bioinformatics and Biomedicine (BIBM)",
    type: "Conference",
    link: "https://doi.org/10.1109/bibm52615.2021.9669527",
  },
  {
    id: "https://openalex.org/W4206758809",
    year: 2021,
    title: "Heart Rate Monitoring Using PPG With Smartphone Camera",
    authors: ["Ayesha, A.", "Qiao, D.", "Zulkernine, F."],
    venue:
      "2021 IEEE International Conference on Bioinformatics and Biomedicine (BIBM)",
    type: "Conference",
    link: "https://doi.org/10.1109/bibm52615.2021.9669735",
  },
  {
    id: "https://openalex.org/W4200044365",
    year: 2021,
    title: "AI in predicting COPD in the Canadian population",
    authors: [
      "Zafari, H.",
      "Langlois, S.",
      "Zulkernine, F.",
      "Kosowan, L.",
      "Singer, A.",
    ],
    venue: "Biosystems",
    type: "Journal",
    link: "https://doi.org/10.1016/j.biosystems.2021.104585",
  },
  {
    id: "https://openalex.org/W4226185317",
    year: 2021,
    title: "FireWarn: Fire Hazards Detection Using Deep Learning Models",
    authors: [
      "Hogan, I.",
      "Qiao, D.",
      "Luo, R.",
      "Moattari, M.",
      "Carthy, A.",
      "Zulkernine, F.",
      "Rivest, F.",
      "Breton, M.",
    ],
    venue:
      "2021 IEEE Third International Conference on Cognitive Machine Intelligence (CogMI)",
    type: "Conference",
    award: "Best Student Paper",
    link: "https://doi.org/10.1109/cogmi52975.2021.00010",
  },
  {
    id: "https://openalex.org/W4205504967",
    year: 2021,
    title: "Detection of Similar Legal Cases on Personal Injury",
    authors: ["Lam, J.", "Chen, Y.", "Zulkernine, F.", "Dahan, S."],
    venue: "2021 International Conference on Data Mining Workshops (ICDMW)",
    type: "Conference",
    award: "Best Paper",
    link: "https://doi.org/10.1109/icdmw53433.2021.00084",
  },
  {
    id: "https://openalex.org/W3206512214",
    year: 2021,
    title: "Incremental Community Detection in Distributed Dynamic Graph",
    authors: ["Abughofa, T.", "Harby, A.", "Isah, H.", "Zulkernine, F."],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "http://arxiv.org/abs/2110.06311",
    pdf: "https://arxiv.org/pdf/2110.06311",
  },
  {
    id: "https://openalex.org/W3215349079",
    year: 2021,
    title:
      "Diagnosing post-traumatic stress disorder using electronic medical record data",
    authors: ["Zafari, H.", "Kosowan, L.", "Zulkernine, F.", "Signer, A."],
    venue: "Health Informatics Journal",
    type: "Journal",
    link: "https://doi.org/10.1177/14604582211053259",
    pdf: "https://journals.sagepub.com/doi/pdf/10.1177/14604582211053259",
  },
  {
    id: "https://openalex.org/W4247201090",
    year: 2021,
    title: "2021 IEEE International Conference on Digital Health",
    authors: [
      "Sheikh, I.",
      "Ahamed, N.",
      "Atukorala, C.",
      "Chang, E.",
      "Damiani, G.",
      "De, P.",
      "Liu, L.",
      "Wang, Z.",
      "Zhang, J.",
      "Zulkernine, F.",
    ],
    venue: "2021 IEEE International Conference on Digital Health (ICDH)",
    type: "Conference",
    link: "https://doi.org/10.1109/icdh52753.2021.00002",
    pdf: "https://ieeexplore.ieee.org/ielx7/9581155/9581058/09581232.pdf",
  },
  {
    id: "https://openalex.org/W3189476076",
    year: 2021,
    title:
      "Patterns of Metastatic Disease in Patients with Cancer Derived from Natural Language Processing of Structured CT Radiology Reports over a 10-year Period",
    authors: [
      "Gian, R.",
      "Lupton, K.",
      "Andrieu, P.",
      "Luthra, A.",
      "Taya, M.",
      "Batch, K.",
      "Nguyen, H.",
      "Rahurkar, P.",
      "Gazit, L.",
      "Nicholas, K.",
      "Fong, C.",
      "Gangai, N.",
      "Schultz, N.",
      "Zulkernine, F.",
      "Sevilimedu, V.",
      "Juluru, K.",
      "Simpson, A.",
      "Hricak, H.",
    ],
    venue: "Radiology",
    type: "Journal",
    link: "https://doi.org/10.1148/radiol.2021210043",
  },
  {
    id: "https://openalex.org/W3205262389",
    year: 2021,
    title: "Incremental Community Detection in Distributed Dynamic Graph",
    authors: ["Abughofa, T.", "Harby, A.", "Isah, H.", "Zulkernine, F."],
    venue:
      "2021 IEEE Seventh International Conference on Big Data Computing Service and Applications (BigDataService)",
    type: "Conference",
    award: "Best Paper",
    link: "https://doi.org/10.1109/bigdataservice52369.2021.00012",
  },
  {
    id: "https://openalex.org/W3191528200",
    year: 2021,
    title: "Chatsum: An Intelligent Medical Chat Summarization Tool",
    authors: ["Zafari, H.", "Zulkernine, F."],
    venue:
      "2021 IEEE EMBS International Conference on Biomedical and Health Informatics (BHI)",
    type: "Conference",
    link: "https://doi.org/10.1109/bhi50953.2021.9508585",
  },
  {
    id: "https://openalex.org/W3179019647",
    year: 2021,
    title:
      "Measuring Heart Rate and Heart Rate Variability with Smartphone Camera",
    authors: [
      "Qiao, D.",
      "Zulkernine, F.",
      "Masroor, R.",
      "Rasool, R.",
      "Jaffar, N.",
    ],
    venue:
      "2021 22nd IEEE International Conference on Mobile Data Management (MDM)",
    type: "Conference",
    link: "https://doi.org/10.1109/mdm52706.2021.00049",
  },
  {
    id: "https://openalex.org/W3160583610",
    year: 2021,
    title:
      "Condition-CNN: A hierarchical multi-label fashion image classification model",
    authors: ["Kolisnik, B.", "Hogan, I.", "Zulkernine, F."],
    venue: "Expert Systems with Applications",
    type: "Journal",
    link: "https://doi.org/10.1016/j.eswa.2021.115195",
  },
  {
    id: "https://openalex.org/W3148865874",
    year: 2021,
    title:
      "Facial Expression Recognition Using a Simplified Convolutional Neural Network Model",
    authors: [
      "Kandeel, A.",
      "Rahmanian, M.",
      "Zulkernine, F.",
      "Abbas, H.",
      "Hassanein, H.",
    ],
    venue:
      "2020 International Conference on Communications, Signal Processing, and their Applications (ICCSPA)",
    type: "Conference",
    link: "https://doi.org/10.1109/iccspa49915.2021.9385739",
  },
  {
    id: "https://openalex.org/W3183056646",
    year: 2021,
    title:
      "Using Deep Learning with Canadian Primary Care Data for Disease Diagnosis",
    authors: [
      "Zafari, H.",
      "Kosowan, L.",
      "Lam, J.",
      "Peeler, W.",
      "Gasmallah, M.",
      "Zulkernine, F.",
      "Singer, A.",
    ],
    venue: "Deep Learning for Biomedical Data Analysis",
    type: "Book Chapter",
    link: "https://doi.org/10.1007/978-3-030-71676-9_12",
  },
  {
    id: "https://openalex.org/W3132664064",
    year: 2020,
    title:
      "Intelligent Transportation System: Managing Pandemic Induced Threats to the People and Economy",
    authors: ["Trivedi, P.", "Zulkernine, F."],
    venue:
      "2020 IEEE 8th International Conference on Smart City and Informatization (iSCI)",
    type: "Conference",
    link: "https://doi.org/10.1109/isci50694.2020.00017",
    pdf: "https://ieeexplore.ieee.org/ielx7/9346290/9346291/09346428.pdf",
  },
  {
    id: "https://openalex.org/W3120453208",
    year: 2020,
    title: "Vision-based Vehicle Detection and Distance Estimation",
    authors: ["Qiao, D.", "Zulkernine, F."],
    venue: "2020 IEEE Symposium Series on Computational Intelligence (SSCI)",
    type: "Journal",
    link: "https://doi.org/10.1109/ssci47803.2020.9308364",
  },
  {
    id: "https://openalex.org/W3157624383",
    year: 2020,
    title:
      "Componentry Analysis of Intelligent Transportation Systems in Smart Cities towards a Connected Future",
    authors: ["Trivedi, P.", "Zulkernine, F."],
    venue:
      "2020 IEEE 22nd International Conference on High Performance Computing and Communications; IEEE 18th International Conference on Smart City; IEEE 6th International Conference on Data Science and Systems (HPCC/SmartCity/DSS)",
    type: "Conference",
    link: "https://doi.org/10.1109/hpcc-smartcity-dss50907.2020.00143",
  },
  {
    id: "https://openalex.org/W3117622895",
    year: 2020,
    title:
      "An Adapter for IBM Streams and Apache Spark to Facilitate Multi-level Data Analytics",
    authors: ["Shi, Y.", "Mahfuz, S.", "Zulkernine, F.", "Nicholls, P."],
    venue:
      "2020 11th IEEE Annual Information Technology, Electronics and Mobile Communication Conference (IEMCON)",
    type: "Conference",
    link: "https://doi.org/10.1109/iemcon51383.2020.9284818",
  },
  {
    id: "https://openalex.org/W4245062221",
    year: 2020,
    title: "SERVICES 2020 Program Committee",
    authors: [
      "Sheikh, I.",
      "Ahsan, G.",
      "Gani, O.",
      "Hasan, K.",
      "Iqbal, A.",
      "Kuroda, T.",
      "Lee, J.",
      "Madiraju, P.",
      "Majumder, A.",
      "Ming, H.",
      "Ni, H.",
      "Rahman, S.",
      "Rahman, M.",
      "Rizzo, J.",
      "Rubin, D.",
      "Shahriar, H.",
      "Takakura, H.",
      "Zulkernine, F.",
    ],
    venue: "2020 IEEE International Conference on Services Computing (SCC)",
    type: "Conference",
    link: "https://doi.org/10.1109/scc49832.2020.00082",
    pdf: "https://ieeexplore.ieee.org/ielx7/9284357/9284451/09284578.pdf",
  },
  {
    id: "https://openalex.org/W3112344197",
    year: 2020,
    title: "Predicting Chronic Obstructive Pulmonary Disease from EMR data",
    authors: [
      "Zafari, H.",
      "Langlois, S.",
      "Zulkernine, F.",
      "Kosowan, L.",
      "Singer, A.",
    ],
    venue:
      "2020 IEEE Conference on Computational Intelligence in Bioinformatics and Computational Biology (CIBCB)",
    type: "Conference",
    link: "https://doi.org/10.1109/cibcb48159.2020.9277712",
  },
  {
    id: "https://openalex.org/W3113022368",
    year: 2020,
    title:
      "Dilated Squeeze-and-Excitation U-Net for Fetal Ultrasound Image Segmentation",
    authors: ["Qiao, D.", "Zulkernine, F."],
    venue:
      "2020 IEEE Conference on Computational Intelligence in Bioinformatics and Computational Biology (CIBCB)",
    type: "Conference",
    link: "https://doi.org/10.1109/cibcb48159.2020.9277667",
  },
  {
    id: "https://openalex.org/W4212831298",
    year: 2020,
    title: "Program Committee Members",
    authors: [
      "Sheikh, I.",
      "Ahsan, G.",
      "Gani, O.",
      "Hasan, K.",
      "Iqbal, A.",
      "Kuroda, T.",
      "Lee, J.",
      "Madiraju, P.",
      "Majumder, A.",
      "Ming, H.",
      "Ni, H.",
      "Rahman, S.",
      "Rahman, M.",
      "Rizzo, J.",
      "Rubin, D.",
      "Shahriar, H.",
      "Takakura, H.",
      "Zulkernine, F.",
    ],
    venue: "2020 IEEE International Conference on Smart Data Services (SMDS)",
    type: "Conference",
    link: "https://doi.org/10.1109/smds49396.2020.00031",
    pdf: "https://ieeexplore.ieee.org/ielx7/9288360/9288479/09288504.pdf",
  },
  {
    id: "https://openalex.org/W4206633064",
    year: 2020,
    title: "SERVICES 2020 Program Committee",
    authors: [
      "Sheikh, I.",
      "Ahsan, G.",
      "Gani, O.",
      "Hasan, K.",
      "Iqbal, A.",
      "Kuroda, T.",
      "Lee, J.",
      "Madiraju, P.",
      "Majumder, A.",
      "Ming, H.",
      "Ni, H.",
      "Rahman, S.",
      "Rahman, M.",
      "Rizzo, J.",
      "Rubin, D.",
      "Shahriar, H.",
      "Takakura, H.",
      "Zulkernine, F.",
    ],
    venue: "2020 IEEE 13th International Conference on Cloud Computing (CLOUD)",
    type: "Conference",
    link: "https://doi.org/10.1109/cloud49709.2020.00099",
    pdf: "https://ieeexplore.ieee.org/ielx7/9284144/9284201/09284297.pdf",
  },
  {
    id: "https://openalex.org/W4206216947",
    year: 2020,
    title: "Program Committee Members",
    authors: [
      "Sheikh, I.",
      "Ahsan, G.",
      "Gani, O.",
      "Hasan, K.",
      "Iqbal, A.",
      "Kuroda, T.",
      "Lee, J.",
      "Madiraju, P.",
      "Majumder, A.",
      "Ming, H.",
      "Ni, H.",
      "Rahman, S.",
      "Rahman, M.",
      "Rizzo, J.",
      "Rubin, D.",
      "Shahriar, H.",
      "Takakura, H.",
      "Zulkernine, F.",
    ],
    venue: "2020 IEEE International Conference on Web Services (ICWS)",
    type: "Conference",
    link: "https://doi.org/10.1109/icws49710.2020.00088",
    pdf: "https://ieeexplore.ieee.org/ielx7/9283848/9283908/09283909.pdf",
  },
  {
    id: "https://openalex.org/W3088315510",
    year: 2020,
    title: "Towards a Natural Language Query Processing System",
    authors: ["Montgomery, C.", "Isah, H.", "Zulkernine, F."],
    venue:
      "2020 1st International Conference on Big Data Analytics and Practices (IBDAP)",
    type: "Conference",
    link: "https://doi.org/10.1109/ibdap50342.2020.9245462",
  },
  {
    id: "https://openalex.org/W3087826863",
    year: 2020,
    title: "A Big Data Lake for Multilevel Streaming Analytics",
    authors: ["Liu, R.", "Isah, H.", "Zulkernine, F."],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "http://arxiv.org/abs/2009.12415",
    pdf: "https://arxiv.org/pdf/2009.12415",
  },
  {
    id: "https://openalex.org/W3096600429",
    year: 2020,
    title: "A Big Data Lake for Multilevel Streaming Analytics",
    authors: ["Liu, R.", "Isah, H.", "Zulkernine, F."],
    venue:
      "2020 1st International Conference on Big Data Analytics and Practices (IBDAP)",
    type: "Conference",
    link: "https://doi.org/10.1109/ibdap50342.2020.9245460",
  },
  {
    id: "https://openalex.org/W3101639274",
    year: 2020,
    title:
      "Determining Worker Type from Legal Text Data using Machine Learning",
    authors: ["Yin, Y.", "Zulkernine, F.", "Dahan, S."],
    venue:
      "2020 IEEE Intl Conf on Dependable, Autonomic and Secure Computing, Intl Conf on Pervasive Intelligence and Computing, Intl Conf on Cloud and Big Data Computing, Intl Conf on Cyber Science and Technology Congress (DASC/PiCom/CBDCom/CyberSciTech)",
    type: "Journal",
    award: "Best Student Paper",
    link: "https://doi.org/10.1109/dasc-picom-cbdcom-cyberscitech49142.2020.00084",
  },
  {
    id: "https://openalex.org/W3099739484",
    year: 2020,
    title:
      "Effects of Pre-trained Word Embeddings on Text-based Deception Detection",
    authors: ["Nam, D.", "Yasmin, J.", "Zulkernine, F."],
    venue:
      "2020 IEEE Intl Conf on Dependable, Autonomic and Secure Computing, Intl Conf on Pervasive Intelligence and Computing, Intl Conf on Cloud and Big Data Computing, Intl Conf on Cyber Science and Technology Congress (DASC/PiCom/CBDCom/CyberSciTech)",
    type: "Journal",
    link: "https://doi.org/10.1109/dasc-picom-cbdcom-cyberscitech49142.2020.00083",
  },
  {
    id: "https://openalex.org/W2999208630",
    year: 2020,
    title: "Traffic Information Detection",
    authors: ["Qiao, D.", "Zhou, J.", "Zulkernine, F."],
    venue: "EasyChair Preprint",
    type: "Preprint",
    link: "https://easychair.org/publications/preprint/mHgj",
  },
  {
    id: "https://openalex.org/W3081627259",
    year: 2020,
    title:
      "The Gap between Deep Learning and Law: Predicting Employment Notice.",
    authors: ["Lam, J.", "Liang, D.", "Dahan, S.", "Zulkernine, F."],
    venue: "Spectrum Research Repository (Concordia University)",
    type: "Journal",
    link: "https://hdl.handle.net/1974/34699",
  },
  {
    id: "https://openalex.org/W2993502775",
    year: 2019,
    title:
      "Diagnosing PTSD using electronic medical records from canadian primary care data",
    authors: [
      "Kaczmarek, E.",
      "Salgo, A.",
      "Zafari, H.",
      "Kosowan, L.",
      "Singer, A.",
      "Zulkernine, F.",
    ],
    venue:
      "Proceedings of the 6th International Conference on Networking, Systems and Security",
    type: "Conference",
    link: "https://doi.org/10.1145/3362966.3362982",
  },
  {
    id: "https://openalex.org/W2995767122",
    year: 2019,
    title:
      "&lt;p&gt;Impact of Fucosylation on Self-Assembly of Prostate and Breast Tumor Spheroids by Using Cyclo-RGDfK(TPP) Peptide and Image Object Detection&lt;/p&gt;",
    authors: [
      "Kalaydina, R.",
      "Zhou, H.",
      "Марквичева, Е.",
      "Burov, S.",
      "Zulkernine, F.",
      "Szewczuk, M.",
    ],
    venue: "OncoTargets and Therapy",
    type: "Journal",
    link: "https://doi.org/10.2147/ott.s235811",
    pdf: "https://www.dovepress.com/getfile.php?fileID=54777",
  },
  {
    id: "https://openalex.org/W2996908621",
    year: 2019,
    title:
      "A Voice Interactive Multilingual Student Support System using IBM Watson",
    authors: ["Ralston, K.", "Chen, Y.", "Isah, H.", "Zulkernine, F."],
    venue:
      "2019 18th IEEE International Conference On Machine Learning And Applications (ICMLA)",
    specialIssue: "Special Session on Education",
    type: "Conference",
    link: "https://doi.org/10.1109/icmla.2019.00309",
  },
  {
    id: "https://openalex.org/W3008764535",
    year: 2019,
    title:
      "Computer Vision for Detecting and Measuring Multicellular Tumor Shperoids of Prostate Cancer",
    authors: [
      "Wojaczek, A.",
      "Kalaydina, R.",
      "Gasmallah, M.",
      "Szewczuk, M.",
      "Zulkernine, F.",
    ],
    venue: "2019 IEEE Symposium Series on Computational Intelligence (SSCI)",
    type: "Journal",
    link: "https://doi.org/10.1109/ssci44817.2019.9002908",
  },
  {
    id: "https://openalex.org/W3004671230",
    year: 2019,
    title: "Smart Phone Based Human Activity Recognition",
    authors: ["Chen, H.", "Mahfuz, S.", "Zulkernine, F."],
    venue:
      "2019 IEEE International Conference on Bioinformatics and Biomedicine (BIBM)",
    specialIssue: "Special Session on Machine Learning in Health",
    type: "Conference",
    link: "https://doi.org/10.1109/bibm47256.2019.8983009",
  },
  {
    id: "https://openalex.org/W2974089011",
    year: 2019,
    title: "A Real-Time Patient Monitoring Framework for Fall Detection",
    authors: ["Ajerla, D.", "Mahfuz, S.", "Zulkernine, F."],
    venue: "Wireless Communications and Mobile Computing",
    specialIssue:
      "Special Issue on Mobile Technologies and Sensor Networks in Healthcare Environments (MSHE)",

    type: "Journal",
    link: "https://doi.org/10.1155/2019/9507938",
    pdf: "https://downloads.hindawi.com/journals/wcmc/2019/9507938.pdf",
  },
  {
    id: "https://openalex.org/W2958805129",
    year: 2019,
    title:
      "A Scalable Framework for Multilevel Streaming Data Analytics using Deep Learning",
    authors: ["Ge, S.", "Isah, H.", "Zulkernine, F.", "Khan, S."],
    venue:
      "2019 IEEE 43rd Annual Computer Software and Applications Conference (COMPSAC)",
    type: "Conference",
    link: "https://doi.org/10.1109/compsac.2019.10205",
  },
  {
    id: "https://openalex.org/W2956462957",
    year: 2019,
    title: "Xu: An Automated Query Expansion and Optimization Tool",
    authors: ["Gallant, M.", "Isah, H.", "Zulkernine, F.", "Khan, S."],
    venue:
      "2019 IEEE 43rd Annual Computer Software and Applications Conference (COMPSAC)",
    type: "Conference",
    link: "https://doi.org/10.1109/compsac.2019.00070",
  },
  {
    id: "https://openalex.org/W2946975908",
    year: 2019,
    title:
      "Stock Market Analysis: A Review and Taxonomy of Prediction Techniques",
    authors: ["Shah, D.", "Isah, H.", "Zulkernine, F."],
    venue: "International Journal of Financial Studies",
    type: "Journal",
    link: "https://doi.org/10.3390/ijfs7020026",
    pdf: "https://www.mdpi.com/2227-7072/7/2/26/pdf?version=1560755357",
  },
  {
    id: "https://openalex.org/W2979325626",
    year: 2019,
    title: "A Survey of Distributed Data Stream Processing Frameworks",
    authors: [
      "Isah, H.",
      "Abughofa, T.",
      "Mahfuz, S.",
      "Ajerla, D.",
      "Zulkernine, F.",
      "Khan, S.",
    ],
    venue: "IEEE Access",
    type: "Journal",
    link: "https://doi.org/10.1109/access.2019.2946884",
    pdf: "https://ieeexplore.ieee.org/ielx7/6287639/8600701/08864052.pdf",
  },
  {
    id: "https://openalex.org/W2944976762",
    year: 2019,
    title: "Fully End-To-End Super-Resolved Bone Age Estimation",
    authors: [
      "Gasmallah, M.",
      "Zulkernine, F.",
      "Rivest, F.",
      "Mousavi, P.",
      "Sedghi, A.",
    ],
    venue: "Lecture notes in computer science",
    type: "Book Chapter",
    link: "https://doi.org/10.1007/978-3-030-18305-9_51",
  },
  {
    id: "https://openalex.org/W3021166220",
    year: 2019,
    title:
      "A hands-on tutorial on deep learning for object and pattern recognition.",
    authors: [
      "Zulkernine, F.",
      "Isah, H.",
      "Mahfuz, S.",
      "Gasmallah, M.",
      "Lam, J.",
      "Khan, S.",
    ],
    venue:
      "Conference of the Centre for Advanced Studies on Collaborative Research",
    type: "Conference",
    link: "https://dblp.uni-trier.de/db/conf/cascon/cascon2019.html#ZulkernineIMGLK19",
  },
  {
    id: "https://openalex.org/W2997193501",
    year: 2018,
    title: "Predicting the Effects of News Sentiments on the Stock Market",
    authors: ["Shah, D.", "Isah, H.", "Zulkernine, F."],
    venue: "2018 IEEE International Conference on Big Data (Big Data)",
    type: "Conference",
    link: "https://doi.org/10.1109/bigdata.2018.8621884",
  },
  {
    id: "https://openalex.org/W2919352243",
    year: 2018,
    title: "Content-based File Type Identification",
    authors: ["Bhat, K.", "Lam, J.", "Zulkernine, F."],
    venue:
      "2018 10th International Conference on Electrical and Computer Engineering (ICECE)",
    type: "Conference",
    link: "https://doi.org/10.1109/icece.2018.8636693",
  },
  {
    id: "https://openalex.org/W2914419771",
    year: 2018,
    title: "A Comparative Study of LSTM and DNN for Stock Market Forecasting",
    authors: ["Shah, D.", "Campbell, W.", "Zulkernine, F."],
    venue: "2018 IEEE International Conference on Big Data (Big Data)",
    type: "Conference",
    link: "https://doi.org/10.1109/bigdata.2018.8622462",
  },
  {
    id: "https://openalex.org/W2995435218",
    year: 2018,
    title: "A Scalable and Robust Framework for Data Stream Ingestion",
    authors: ["Isah, H.", "Zulkernine, F."],
    venue: "2018 IEEE International Conference on Big Data (Big Data)",
    type: "Conference",
    link: "https://doi.org/10.1109/bigdata.2018.8622360",
  },
  {
    id: "https://openalex.org/W2909408920",
    year: 2018,
    title: "Video Predictive Object Detector",
    authors: ["Gasmallah, M.", "Zulkernine, F."],
    venue:
      "2018 IEEE 9th Annual Information Technology, Electronics and Mobile Communication Conference (IEMCON)",
    type: "Conference",
    link: "https://doi.org/10.1109/iemcon.2018.8615054",
  },
  {
    id: "https://openalex.org/W2901750619",
    year: 2018,
    title:
      "Detecting Irregular Patterns in IoT Streaming Data for Fall Detection",
    authors: ["Mahfuz, S.", "Isah, H.", "Zulkernine, F.", "Nicholls, P."],
    venue:
      "2018 IEEE 9th Annual Information Technology, Electronics and Mobile Communication Conference (IEMCON)",
    type: "Conference",
    link: "https://doi.org/10.1109/iemcon.2018.8614822",
  },
  {
    id: "https://openalex.org/W2903748818",
    year: 2018,
    title: "Large-scale multilevel streaming data analytics",
    authors: [
      "Zulkernine, F.",
      "Isah, H.",
      "Givigi, S.",
      "Liu, Y.",
      "Shim, E.",
      "Elsayed, M.",
    ],
    venue: "Computer Science and Software Engineering",
    type: "Conference",
    link: "https://dblp.uni-trier.de/db/conf/cascon/cascon2018.html#ZulkernineIGLSE08",
  },
  {
    id: "https://openalex.org/W2891469708",
    year: 2018,
    title:
      "The use of Virtual Reality in Enhancing Interdisciplinary Research and Education",
    authors: ["Leung, T.", "Zulkernine, F.", "Isah, H."],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "http://arxiv.org/abs/1809.08585",
    pdf: "https://arxiv.org/pdf/1809.08585",
  },
  {
    id: "https://openalex.org/W2889029163",
    year: 2018,
    title: "Automated Query Expansion using High Dimensional Clustering.",
    authors: ["Gallant, M.", "Isah, H.", "Zulkernine, F."],
    venue: "arXiv (Cornell University)",
    type: "Preprint",
    link: "https://arxiv.org/pdf/1808.09353.pdf",
  },
  {
    id: "https://openalex.org/W2887611685",
    year: 2018,
    title:
      "Detecting Low Back Pain from Clinical Narratives Using Machine Learning Approaches",
    authors: [
      "Judd, M.",
      "Zulkernine, F.",
      "Wolfrom, B.",
      "Barber, D.",
      "Rajaram, A.",
    ],
    venue: "Communications in computer and information science",
    type: "Book Chapter",
    link: "https://doi.org/10.1007/978-3-319-99133-7_10",
  },
  {
    id: "https://openalex.org/W2885457307",
    year: 2018,
    title: "Sprouter: Dynamic Graph Processing over Data Streams at Scale",
    authors: ["Abughofa, T.", "Zulkernine, F."],
    venue: "Lecture notes in computer science",
    type: "Book Chapter",
    link: "https://doi.org/10.1007/978-3-319-98812-2_28",
  },
  {
    id: "https://openalex.org/W2984694537",
    year: 2018,
    title:
      "Detecting Low Back Pain from Clinical Narratives Using Machine Learning Approaches.",
    authors: [
      "Judd, M.",
      "Zulkernine, F.",
      "Wolfrom, B.",
      "Barber, D.",
      "Rajaram, A.",
    ],
    venue:
      "20th International Conference on Big Data Analytics and Knowledge Discovery (DEXA)",
    type: "Conference",
    link: "https://dblp.uni-trier.de/db/conf/dexaw/bdmics2018.html#JuddZWBR18",
  },
  {
    id: "https://openalex.org/W2783503111",
    year: 2017,
    title: "Towards online graph processing with spark streaming",
    authors: ["Abughofa, T.", "Zulkernine, F."],
    venue: "2017 IEEE International Conference on Big Data (Big Data)",
    type: "Conference",
    link: "https://doi.org/10.1109/bigdata.2017.8258245",
  },
  {
    id: "https://openalex.org/W2783342416",
    year: 2017,
    title:
      "Leveraging distributed big data storage support in CLAaaS for WINGS workflow management system",
    authors: ["Alghamdi, H.", "Zulkernine, F.", "Martin, P."],
    venue: "2017 IEEE International Conference on Big Data (Big Data)",
    type: "Conference",
    link: "https://doi.org/10.1109/bigdata.2017.8258200",
  },
  {
    id: "https://openalex.org/W2782775921",
    year: 2017,
    title: "Towards building a hybrid model for predicting stock indexes",
    authors: ["Creighton, J.", "Zulkernine, F."],
    venue: "2017 IEEE International Conference on Big Data (Big Data)",
    type: "Conference",
    link: "https://doi.org/10.1109/bigdata.2017.8258433",
  },
  {
    id: "https://openalex.org/W2785314181",
    year: 2017,
    title: "Lexa: A tool for detecting dyslexia through auditory processing",
    authors: ["Poole, A.", "Zulkernine, F.", "Aylward, C."],
    venue: "2017 IEEE Symposium Series on Computational Intelligence (SSCI)",
    type: "Journal",
    link: "https://doi.org/10.1109/ssci.2017.8285191",
  },
  {
    id: "https://openalex.org/W2785593625",
    year: 2017,
    title:
      "Particle swarm optimization for large-scale clustering on apache spark",
    authors: ["Sherar, M.", "Zulkernine, F."],
    venue: "2017 IEEE Symposium Series on Computational Intelligence (SSCI)",
    type: "Journal",
    link: "https://doi.org/10.1109/ssci.2017.8285208",
  },
  {
    id: "https://openalex.org/W2584069253",
    year: 2016,
    title: "BINARY: A framework for big data integration for ad-hoc querying",
    authors: ["Eftekhari, A.", "Zulkernine, F.", "Martin, P."],
    venue: "2016 IEEE International Conference on Big Data (Big Data)",
    type: "Conference",
    link: "https://doi.org/10.1109/bigdata.2016.7840922",
  },
  {
    id: "https://openalex.org/W2584745936",
    year: 2016,
    title:
      "Predicting Movie Box Office Profitability: A Neural Network Approach",
    authors: ["Rhee, T.", "Zulkernine, F."],
    venue:
      "2016 15th IEEE International Conference on Machine Learning and Applications (ICMLA)",
    type: "Conference",
    link: "https://doi.org/10.1109/icmla.2016.0117",
  },
  {
    id: "https://openalex.org/W2588815870",
    year: 2016,
    title:
      "Using machine learning to predict hypertension from a clinical dataset",
    authors: ["LaFreniere, D.", "Zulkernine, F.", "Barber, D.", "Martin, K."],
    venue: "2016 IEEE Symposium Series on Computational Intelligence (SSCI)",
    type: "Journal",
    link: "https://doi.org/10.1109/ssci.2016.7849886",
  },
  {
    id: "https://openalex.org/W2593837619",
    year: 2016,
    title:
      "Proactive auto-scaling of resources for stream processing engines in the cloud",
    authors: ["Ahmed, T.", "Zulkernine, F.", "Cordy, J."],
    venue: "Computer Science and Software Engineering",
    type: "Conference",
    link: "https://dblp.uni-trier.de/db/conf/cascon/cascon2016.html#AhmedZC16",
  },
  {
    id: "https://openalex.org/W2592666706",
    year: 2016,
    title:
      "ArchiGen: a conceptual form design tool using an evolutionary computing approach",
    authors: ["Chan, A.", "Zulkernine, F."],
    venue: "Computer Science and Software Engineering",
    type: "Conference",
    link: "https://dblp.uni-trier.de/db/conf/cascon/cascon2016.html#ChanZ16",
  },
  {
    id: "https://openalex.org/W1694855557",
    year: 2015,
    title:
      "Cost-Effective Resource Configurations for Multi-Tenant Database Systems in Public Clouds",
    authors: [
      "Mian, R.",
      "Martin, P.",
      "Zulkernine, F.",
      "Vázquez‐Poletti, J.",
    ],
    venue: "International Journal of Cloud Applications and Computing",
    type: "Journal",
    link: "https://doi.org/10.4018/ijcac.2015040101",
  },
  {
    id: "https://openalex.org/W138212971",
    year: 2013,
    title:
      "Analytics-as-a-service: confluence of big data, cloud computing and software-as-a-service",
    authors: [
      "Martin, P.",
      "Zulkernine, F.",
      "Khalifa, S.",
      "Eftekhari, A.",
      "Ashtiani, B.",
      "Rope, D.",
      "McRoberts, M.",
      "Statchuk, C.",
    ],
    venue:
      "Conference of the Centre for Advanced Studies on Collaborative Research",
    type: "Conference",
    link: "https://dblp.uni-trier.de/db/conf/cascon/cascon2013.html#MartinZKEARMS13",
  },
  {
    id: "https://openalex.org/W2038928885",
    year: 2013,
    title: "CAPRI: A Tool for Mining Complex Line Patterns in Large Log Data",
    authors: [
      "Zulkernine, F.",
      "Martin, P.",
      "Powley, W.",
      "Soltani, S.",
      "Mankovskii, S.",
      "Addleman, M.",
    ],
    venue:
      "Proceedings of the 2nd International Workshop on Big Data, Streams and Heterogeneous Source Mining: Algorithms, Systems, Programming Models and Applications",
    type: "Conference",
    link: "https://doi.org/10.1145/2501221.2501228",
  },
  {
    id: "https://openalex.org/W1980764417",
    year: 2013,
    title:
      "Towards Cloud-Based Analytics-as-a-Service (CLAaaS) for Big Data Analytics in the Cloud",
    authors: [
      "Zulkernine, F.",
      "Martin, P.",
      "Zou, Y.",
      "Bauer, M.",
      "Gwadry‐Sridhar, F.",
      "Aboulnaga, A.",
    ],
    venue: "2013 IEEE International Congress on Big Data",
    type: "Journal",
    link: "https://doi.org/10.1109/bigdata.congress.2013.18",
  },
  {
    id: "https://openalex.org/W2146212558",
    year: 2013,
    title:
      "Towards building performance models for data-intensive workloads in public clouds",
    authors: [
      "Mian, R.",
      "Martin, P.",
      "Zulkernine, F.",
      "Vázquez‐Poletti, J.",
    ],
    venue:
      "Proceedings of the 4th ACM/SPEC International Conference on Performance Engineering",
    type: "Conference",
    link: "https://doi.org/10.1145/2479871.2479908",
  },
  {
    id: "https://openalex.org/W2054670927",
    year: 2012,
    title:
      "Estimating resource costs of data-intensive workloads in public clouds",
    authors: [
      "Mian, R.",
      "Martin, P.",
      "Zulkernine, F.",
      "Vázquez‐Poletti, J.",
    ],
    venue:
      "Proceedings of the 10th International Workshop on Middleware for Grids, Clouds and e-Science",
    type: "Conference",
    link: "https://doi.org/10.1145/2405136.2405139",
  },
  {
    id: "https://openalex.org/W69059961",
    year: 2012,
    title: "Ultra-large scale services",
    authors: ["Martin, P.", "Zulkernine, F."],
    venue:
      "Conference of the Centre for Advanced Studies on Collaborative Research",
    type: "Conference",
    link: "https://dblp.uni-trier.de/db/conf/cascon/cascon2012.html#MartinZ12",
  },
  {
    id: "https://openalex.org/W1972643115",
    year: 2012,
    title:
      "Towards a Training-Oriented Adaptive Decision Guidance and Support System",
    authors: [
      "Zulkernine, F.",
      "Martin, P.",
      "Soltani, S.",
      "Powley, W.",
      "Mankovskii, S.",
      "Addleman, M.",
    ],
    venue:
      "2012 IEEE 28th International Conference on Data Engineering Workshops",
    type: "Conference",
    link: "https://doi.org/10.1109/icdew.2012.74",
  },
  {
    id: "https://openalex.org/W2005077466",
    year: 2012,
    title:
      "A Constraint-Driven Business Object Model for Service-Based Business Processes",
    authors: [
      "Zulkernine, F.",
      "Bertoli, P.",
      "Pistore, M.",
      "Friesen, A.",
      "Lemcke, J.",
      "Thimmel, B.",
      "Geisau, O.",
    ],
    venue:
      "2012 Ninth International Conference on Information Technology - New Generations",
    type: "Conference",
    link: "https://doi.org/10.1109/itng.2012.170",
  },
  {
    id: "https://openalex.org/W2489605283",
    year: 2011,
    title: "Web Services Management",
    authors: ["Zulkernine, F.", "Martin, P."],
    venue: "IGI Global eBooks",
    type: "Book Chapter",
    link: "https://doi.org/10.4018/978-1-60566-092-9.ch022",
  },
  {
    id: "https://openalex.org/W4256327710",
    year: 2011,
    title: "Web Services Management",
    authors: ["Zulkernine, F.", "Martin, P."],
    venue: "IGI Global eBooks",
    type: "Book Chapter",
    link: "https://doi.org/10.4018/9781599042282.ch012",
  },
  {
    id: "https://openalex.org/W2118448117",
    year: 2010,
    title:
      "An Adaptive and Intelligent SLA Negotiation System for Web Services",
    authors: ["Zulkernine, F.", "Martin, P."],
    venue: "IEEE Transactions on Services Computing",
    type: "Journal",
    link: "https://doi.org/10.1109/tsc.2010.44",
  },
  {
    id: "https://openalex.org/W3013718812",
    year: 2009,
    title:
      "A Design Theory Approach to Building Strategic Network‐Based Customer Service Systems*",
    authors: [
      "Brohman, M.",
      "Piccoli, G.",
      "Martin, P.",
      "Zulkernine, F.",
      "Parasuraman, A.",
      "Watson, R.",
    ],
    venue: "Decision Sciences",
    specialIssue:
      "Special Topic Forum: Advancing Decision Making in Service Innovation",
    award: "Best Article (Nominated)",
    type: "Journal",
    link: "https://doi.org/10.1111/j.1540-5915.2009.00242.x",
  },
  {
    id: "https://openalex.org/W2129249330",
    year: 2009,
    title: "A Policy-Based Middleware for Web Services SLA Negotiation",
    authors: ["Zulkernine, F.", "Martin, P.", "Craddock, C.", "Wilson, K."],
    venue: "2009 IEEE International Conference on Web Services",
    type: "Conference",
    link: "https://doi.org/10.1109/icws.2009.157",
  },
  {
    id: "https://openalex.org/W106368060",
    year: 2009,
    title: "Autonomic Management of Networked Web Services-Based Processes",
    authors: ["Zulkernine, F.", "Powley, W.", "Martin, P."],
    venue: "Autonomic Computing and Networking",
    type: "Book Chapter",
    link: "https://doi.org/10.1007/978-0-387-89828-5_14",
  },
  {
    id: "https://openalex.org/W2107468433",
    year: 2009,
    title:
      "A comprehensive service management middleware for autonomic management of composite web services-based processes",
    authors: ["Zulkernine, F."],
    venue: "QSpace (Queen's University Library)",
    type: "Other",
    link: "http://hdl.handle.net/1974/1764",
    pdf: "http://hdl.handle.net/1974/1764",
  },
  {
    id: "https://openalex.org/W2130633327",
    year: 2008,
    title:
      "A Middleware Solution to Monitoring Composite Web Services-Based Processes",
    authors: ["Zulkernine, F.", "Martin, P.", "Wilson, K."],
    venue: "2008 IEEE Congress on Services Part II (services-2 2008)",
    type: "Journal",
    link: "https://doi.org/10.1109/services-2.2008.10",
  },
  {
    id: "https://openalex.org/W2551618716",
    year: 2008,
    title: "Architecture for an Autonomic Web Services Environment",
    authors: [
      "Tian, W.",
      "Zulkernine, F.",
      "Zebedee, J.",
      "Powley, W.",
      "Martin, P.",
    ],
    venue: "http://www.cs.queensu.ca/home/cords/wsmdeis.pdf",
    type: "Journal",
    link: "http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.85.4924",
  },
  {
    id: "https://openalex.org/W2127158403",
    year: 2007,
    title: "Reputation-Enhanced QoS-based Web Services Discovery",
    authors: ["Xu, Z.", "Martin, P.", "Powley, W.", "Zulkernine, F."],
    venue: "IEEE International Conference on Web Services (ICWS 2007)",
    type: "Conference",
    link: "https://doi.org/10.1109/icws.2007.152",
  },
  {
    id: "https://openalex.org/W4247180404",
    year: 2007,
    title: "Web Services Management",
    authors: ["Zulkernine, F.", "Martin, P."],
    venue: "IGI Global eBooks",
    type: "Book Chapter",
    link: "https://doi.org/10.4018/978-1-59904-228-2.ch012",
  },
  {
    id: "https://openalex.org/W2006178006",
    year: 2007,
    title:
      "Conceptual Framework for a Comprehensive Service Management Middleware",
    authors: ["Zulkernine, F.", "Martin, P."],
    venue:
      "21st International Conference on Advanced Information Networking and Applications Workshops (AINAW'07)",
    type: "Conference",
    link: "https://doi.org/10.1109/ainaw.2007.125",
  },
  {
    id: "https://openalex.org/W1532678084",
    year: 2005,
    title: "Architecture for an Autonomic Web Services Environment",
    authors: [
      "Tian, W.",
      "Zulkernine, F.",
      "Zebedee, J.",
      "Powley, W.",
      "Martin, P.",
    ],
    venue:
      "Proceedings of the Joint Workshop on Web Services and Model-Driven Enterprise Information Systems",
    type: "Conference",
    link: "https://doi.org/10.5220/0002561400540066",
  },
];
